services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: adocao
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  ms-adocao:
    build:
      context: ./src
      dockerfile: Adocao.Web/Dockerfile
    depends_on:
      - mysql
    environment:
      - DB_TYPE=mysql
      - DB_CONNECTION_STRING=Server=mysql;Port=3307;Database=adocao;User Id=root;Password=root;SslMode=None;AllowPublicKeyRetrieval=True;TreatTinyAsBoolean=false;
    ports:
      - "8080:8080"

volumes:
  mysql_data: